# Generated by Django 4.2.30 on 2026-07-27 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_default_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSDeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, db_index=True, max_length=50)),
                ('status_code', models.CharField(blank=True, max_length=20)),
                ('network_code', models.CharField(blank=True, db_index=True, max_length=30)),
                ('failure_reason', models.CharField(blank=True, max_length=150)),
                ('retry_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cost', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_delivery_reports', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_delivery_reports', to='accounts.verificationcode')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['status', 'updated_at'], name='accounts_sm_status_81530a_idx'), models.Index(fields=['phone', 'updated_at'], name='accounts_sm_phone_a4fa56_idx')],
            },
        ),
    ]
