# Generated by Django 4.2.30 on 2026-06-04 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', 'Scam or Fraud'), ('duplicate', 'Duplicate Listing'), ('wrong_category', 'Wrong Category'), ('prohibited', 'Prohibited Item'), ('sold_but_active', 'Sold but Still Active'), ('other', 'Other')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_listing_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', 'is_resolved'], name='moderation__listing_1534b6_idx'), models.Index(fields=['reporter', 'created_at'], name='moderation__reporte_cfdb8d_idx'), models.Index(fields=['reason', 'is_resolved'], name='moderation__reason_be982a_idx')],
                'unique_together': {('listing', 'reporter', 'reason')},
            },
        ),
    ]
