# Generated by Django 4.2.30 on 2026-06-25 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_chatmessageattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('scam', 'Scam'), ('abuse', 'Abuse'), ('harassment', 'Harassment'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_chat_reports', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chats.chatthread')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['thread', '-created_at'], name='chats_chatr_thread__905a96_idx'), models.Index(fields=['reporter', '-created_at'], name='chats_chatr_reporte_826479_idx'), models.Index(fields=['reported_user', '-created_at'], name='chats_chatr_reporte_95c143_idx'), models.Index(fields=['is_resolved', '-created_at'], name='chats_chatr_is_reso_08a80b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_blocks_made', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='chats.chatthread')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', 'blocked_user'], name='chats_chatb_blocker_172895_idx'), models.Index(fields=['thread', 'is_active'], name='chats_chatb_thread__1d5d30_idx')],
                'unique_together': {('blocker', 'blocked_user', 'thread')},
            },
        ),
    ]
