# Generated by Django 4.2.30 on 2026-07-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chatthreadparticipantstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chats.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatthreadparticipantstate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
