# Generated by Django 4.2.30 on 2026-06-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package_type', models.CharField(choices=[('featured_listing', 'Featured Listing'), ('boost_listing', 'Boost Listing'), ('homepage_promotion', 'Homepage Promotion'), ('subscription', 'Subscription')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'price', 'name'],
                'indexes': [models.Index(fields=['package_type', 'is_active'], name='payments_pr_package_6dc369_idx')],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.promotionpackage'),
        ),
    ]
