# Generated by Django 4.2.30 on 2026-07-27 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='locations.city')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='locations_a_slug_a4b053_idx'), models.Index(fields=['is_active'], name='locations_a_is_acti_270b07_idx'), models.Index(fields=['city', 'is_active'], name='locations_a_city_id_a15902_idx')],
                'unique_together': {('city', 'slug')},
            },
        ),
    ]
