# Generated by Django 4.2.30 on 2026-06-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_featured_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('active', 'Active'), ('unavailable', 'Unavailable'), ('rejected', 'Rejected'), ('sold', 'Sold'), ('expired', 'Expired'), ('deleted', 'Deleted')], db_index=True, default='pending', max_length=20),
        ),
    ]
