# Generated by Django 4.2.30 on 2026-07-22 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0004_pendinglistingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinglistingimage',
            name='reserved_for_draft',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ListingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('staged_image_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing_draft', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
