# Generated by Django 4.2.30 on 2026-07-24 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_listing_image_crop_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30, 'Ad description must be at least 30 characters.')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=180, validators=[django.core.validators.MinLengthValidator(10, 'Ad title must be at least 10 characters.')]),
        ),
    ]
