# Generated by Django 4.2.30 on 2026-07-27 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_seed_kampala_divisions'),
        ('listings', '0013_listing_review_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.area'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['area', 'status'], name='listings_li_area_id_d57cbf_idx'),
        ),
    ]
