# Generated by Django 4.2.30 on 2026-07-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_listing_area_listing_listings_li_area_id_d57cbf_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='shares_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
