"""Uganda sub-counties, towns and municipal divisions grouped by QOT city.

Source: ATC Uganda Administrative Boundaries, Uganda Sub Counties layer.
The dataset is stored locally so deployments and location forms do not depend on
third-party network availability.
"""

UGANDA_AREAS_SOURCE_URL = (
    "https://services7.arcgis.com/gYHOe4V6gFqvbVJj/ArcGIS/rest/services/"
    "ATC_Uganda_Admin_Boundaries/FeatureServer/0"
)

UGANDA_AREAS = {'adjumani': ['Adjumani Town Council',
              'Adropi',
              'Arinyapi',
              'Ciforo',
              'Dzaipi',
              'Itirikwa',
              'Ofua',
              'Pacara',
              'Pakele',
              'Ukusijoni'],
 'agago': ['Adilang',
           'Agago Town Council',
           'Arum',
           'Kalongo Town Council',
           'Kotomol',
           'Lamiyo',
           'Lapono',
           'Lira Palwo',
           'Lokole',
           'Omiya Pacwa',
           'Omot',
           'Paimol',
           'Parabongo',
           'Patongo',
           'Patongo Town Council',
           'Wol'],
 'alebtong': ['Abako',
              'Abia',
              'Akura',
              'Alebtong Town Council',
              'Aloi',
              'Amugu',
              'Apala',
              'Awei',
              'Omoro'],
 'amolatar': ['Agikdak',
              'Agwingiri',
              'Akwon',
              'Amolatar Town Council',
              'Aputi',
              'Arwotcek',
              'Awelo',
              'Etam',
              'Muntu',
              'Namasale',
              'Namasale Town Council'],
 'amudat': ['Amudat', 'Amudat Town Council', 'Karita', 'Loroo'],
 'amuru': ['Amuru', 'Amuru Town Council', 'Attiak', 'Lamogi', 'Pabo'],
 'apac': ['Agulu Division',
          'Akere Division',
          'Akokoro',
          'Apac',
          'Arocha Division',
          'Atik Division',
          'Chegere',
          'Ibuje'],
 'arua': ['Adumi',
          'Aii-Vu',
          'Ajia',
          'Arivu',
          'Aroi',
          'Arua Hill Division',
          'Ayivuni',
          'Bileafe',
          'Dadamu',
          'Katrini',
          'Logiri',
          'Manibe',
          'Odupi',
          'Oluko',
          'Omugo',
          'Pajulu',
          'River Oli Division',
          'Uriama',
          'Vurra'],
 'budaka': ['Budaka',
            'Budaka Town Council',
            'Iki-Iki',
            'Kachomo',
            'Kaderuna',
            'Kakule',
            'Kameruka',
            'Kamonkoli',
            'Katiira',
            'Lyama',
            'Mugiti',
            'Naboa',
            'Nansanga'],
 'bududa': ['Bubiita',
            'Bududa',
            'Bududa Town Council',
            'Bukalasi',
            'Bukibokolo',
            'Bukigai',
            'Bulucheke',
            'Bumasheti',
            'Bumayoka',
            'Bushika',
            'Bushiribo',
            'Bushiyi',
            'Buwali',
            'Nabweya',
            'Nakatsi',
            'Nalwanza',
            'Nangako Town Council'],
 'bugiri': ['Budhaya',
            'Bulesa',
            'Bulidha',
            'Buluguyi',
            'Buwunga',
            'Eastern Division',
            'Iwemba',
            'Kapyanga',
            'Muterere',
            'Nabukalu',
            'Nankoma',
            'Western Division'],
 'buhweju': ['Bihanga',
             'Bitsya',
             'Burere',
             'Engaju',
             'Karungu',
             'Nsiika Town Council',
             'Nyakishana',
             'Rwengwe'],
 'buikwe': ['Buikwe',
            'Buikwe Town Council',
            'Central Division',
            'Kawolo Division',
            'Najja',
            'Najjembe Division',
            'Ngogwe',
            'Njeru Division',
            'Nkokonjeru Town Council',
            'Nyenga Division',
            'Ssi-Bukunja',
            'Wakisi Division'],
 'bukedea': ['Bukedea', 'Bukedea Town Council', 'Kachumbala', 'Kidongole', 'Kolir', 'Malera'],
 'bukomansimbi': ['Bigasa', 'Bukomansimbi  Town Council', 'Butenga', 'Kibinge', 'Kitanda'],
 'bukwo': ['Bukwo',
           'Bukwo Town Council',
           'Chepkwasta',
           'Chesower',
           'Kabei',
           'Kamet',
           'Kaptererwo',
           'Kortek',
           'Riwo',
           'Senendet',
           'Suam',
           'Tulel'],
 'bulambuli': ['Buginyanya',
               'Bukhalu',
               'Bulaago',
               'Bulambuli Town Council',
               'Bulegeni',
               'Bulegeni Town Council',
               'Buluganya',
               'Bumasobo',
               'Bumugibole',
               'Bunambutye',
               'Buyaga Town Council',
               'Bwikhonge',
               'Kamu',
               'Lusha',
               'Masiira',
               'Muyembe',
               'Nabbongo',
               'Namisuni',
               'Simu',
               'Sisiyi'],
 'buliisa': ['Biiso',
             'Buliisa',
             'Buliisa Town Council',
             'Butiaba',
             'Kigwera',
             'Kihungya',
             'Ngwedo'],
 'bundibugyo': ['Bubandi',
                'Bubukwanga',
                'Buganikire Town Councili',
                'Bukonzo',
                'Bundibugyo Town Council',
                'Bundingoma',
                'Burondo',
                'Busaru',
                'Busunga Twon Council',
                'Butama-Mitunda Town Council',
                'Harugale',
                'Kagugu',
                'Kasitu',
                'Kirumya',
                'Kisubba',
                'Mabere',
                'Mirambi',
                'Nduguto',
                'Ngamba',
                'Ntandi Town Council',
                'Ntotoro',
                'Nyahuka Town Council',
                'Sindila',
                'Tokwe'],
 'bunyangabu': ['Buheesi',
                'Buheesi Town Council',
                'Kabonero',
                'Katebwa',
                'Kibiito',
                'Kibiito Town Council',
                'Kisomoro',
                'Kiyombya',
                'Kyamukube Town Council',
                'Rubona Town Council',
                'Rwimi',
                'Rwimi Town Council'],
 'bushenyi': ['Bitooma',
              'Bumbaire',
              'Central Divison',
              'Ibaare',
              'Ishaka Divison',
              'Kakanju',
              'Kyabugimbi',
              'Kyamuhunga',
              'Kyamuhunga Town Council',
              'Kyeizooba',
              'Nyabubare',
              'Nyakabirizi Division',
              'Ruhumuro',
              'Rwentuha Town Council'],
 'busia': ['Buhehe',
           'Bulumbi',
           'Busime',
           'Busitema',
           'Buteba',
           'Buyanga',
           'Dabani',
           'Eastern Division',
           'Lumino',
           'Lunyo',
           'Majanji',
           'Masaba',
           'Masafu',
           'Masinya',
           'Sikuda',
           'Western Division'],
 'butaleja': ['Budumba',
              'Busaba',
              'Busabi',
              'Busolwe',
              'Busolwe Town Council',
              'Butaleja',
              'Butaleja Town Council',
              'Himutu',
              'Kachonga',
              'Mazimasa',
              'Nawanjofu',
              'Naweyo'],
 'butambala': ['Budde', 'Bulo', 'Gombe Town Council', 'Kalamba', 'Kibibi', 'Ngando'],
 'buvuma': ['Bugaya',
            'Busamuzi',
            'Buvuma Town Council',
            'Buwooya',
            'Bweema',
            'Lubya',
            'Lwajje',
            'Lyabaana',
            'Nairambi'],
 'buyende': ['Bugaya', 'Buyende', 'Buyende Town Council', 'Kagulu', 'Kidera', 'Nkondo'],
 'dokolo': ['Adeknino',
            'Adok',
            'Agwata',
            'Amwoma',
            'Batta',
            'Dokolo',
            'Dokolo Tc',
            'Kangai',
            'Kwera',
            'Okwalongwen',
            'Okwongodul'],
 'entebbe': ['Division A', 'Division B'],
 'fort-portal': ['Eastern Division', 'Southern Division', 'Western Division'],
 'gomba': ['Kabulasoke', 'Kanoni Town Council', 'Kyegonza', 'Maddu', 'Mpenja'],
 'gulu': ['Awach',
          'Bar Dege Division',
          'Bungatira',
          'Laroo Division',
          'Layibi Division',
          'Paicho',
          'Palaro',
          'Patiko',
          'Pece Division',
          'Unyama'],
 'hoima': ['Buhanika',
           'Bujumbura Division',
           'Buseruka',
           'Busiisi Division',
           'Kahoora Divison',
           'Kigorobya',
           'Kigorobya Town Council',
           'Kitoba',
           'Kyabigambire',
           'Mparo Divison'],
 'ibanda': ['Bisheshe Division',
            'Bufunda Division',
            'Igorora Town Council',
            'Ishongororo',
            'Ishongororo Town Council',
            'Kagango Division',
            'Keihangara',
            'Kicuzi',
            'Kijongo',
            'Kikyenkye',
            'Nyabuhikye',
            'Nyamarebe',
            'Rukiri',
            'Rushango Town Council',
            'Rwenkoba Town Council'],
 'iganga': ['Bulamogi',
            'Central Division',
            'Nabitende',
            'Nakalama',
            'Nakigo',
            'Nambale',
            'Namungalwe',
            'Nawandala',
            'Nawanyingi',
            'Northern Division'],
 'isingiro': ['Birere',
              'Endiinzi',
              'Endiinzi Town Council',
              'Isingiro Town Council',
              'Kaberebere Town Council',
              'Kabingo',
              'Kabuyanda',
              'Kabuyanda Town Council',
              'Kakamba',
              'Kashumba',
              'Kikagate',
              'Masha',
              'Mbaare',
              'Ngarama',
              'Nyakitunda',
              'Nyamuyanja',
              'Ruborogota',
              'Rugaaga',
              'Rushasha'],
 'jinja': ['Budondo',
           'Bugembe Town Council',
           'Busedde',
           'Butagaya',
           'Buwenge',
           'Buwenge Town Council',
           'Buyengo',
           'Central Division',
           'Kakira Town Council',
           'Mafubira',
           'Masese Walukuba',
           'Mpumudde Division'],
 'kaabong': ['Kaabong East',
             'Kaabong Town Council',
             'Kaabong West',
             'Kakamar',
             'Kalapata',
             'Kamion',
             'Kathile',
             'Kathile South',
             'Lodiko',
             'Lolelia',
             'Lotim',
             'Loyoro',
             'Sidok'],
 'kabale': ['Buhara',
            'Butanda',
            'Central Division',
            'Kaharo',
            'Kamuganguzi',
            'Katuna Town Council',
            'Kitumba',
            'Kyanamira',
            'Maziba',
            'Northern Division',
            'Rubaya',
            'Ryakirimira Town Council',
            'Southern Division'],
 'kabarole': ['Bukuuku',
              'Busoro',
              'Eastern Division',
              'Hakibaale',
              'Harugogo',
              'Karago Town Council',
              'Karambi',
              'Karangura',
              'Kasenda',
              'Kicwamba',
              'Kijura Town Council',
              'Kiko Town Council',
              'Mabende',
              'Mugusu',
              'Mugusu Town Council',
              'Ruteete',
              'Southern Division',
              'Western Division'],
 'kaberamaido': ['Alwa',
                 'Aperkira',
                 'Kaberamaido',
                 'Kaberamaido Town Council',
                 'Kobulubulu',
                 'Ochero'],
 'kagadi': ['Burora',
            'Bwikara',
            'Kabamba',
            'Kagadi',
            'Kagadi  Town Council',
            'Kiryanga',
            'Kyakabadiima',
            'Kyanaisoke',
            'Kyaterekera',
            'Kyenzige',
            'Mabaale',
            'Mabaale Town Council',
            'Mpeefu',
            'Muhorro',
            'Muhorro  Town Council',
            'Ndaiga',
            'Paacwa',
            'Rugashari',
            'Ruteete'],
 'kakumiro': ['Birembo',
              'Bwanswa',
              'Kakindo',
              'Kakumiro  Town Council',
              'Kasambya',
              'Katikara',
              'Kijangi',
              'Kikwaya',
              'Kisiita',
              'Kisiita Town Council',
              'Kitaihuka',
              'Mpasaana',
              'Nalweyo',
              'Nkooko'],
 'kalangala': ['Bubeke',
               'Bufumira',
               'Bujumba',
               'Kalangala Town Council',
               'Kyamuswa',
               'Mazinga',
               'Mugoye'],
 'kaliro': ['Budomero',
            'Bukamba',
            'Bumanya',
            'Buyinda',
            'Gadumire',
            'Kaliro Town Council',
            'Kasokwe',
            'Kisinda',
            'Namugongo',
            'Namwiwa',
            'Nansololo',
            'Nawaikoke'],
 'kalungu': ['Bukulula',
             'Kalungu',
             'Kalungu Town Council',
             'Kyamulibwa',
             'Kyamulibwa Town Council',
             'Lukaya Town Council',
             'Lwabenge'],
 'kampala': ['Central',
             'Kawempe',
             'Makindye',
             'Nakawa',
             'Rubaga'],
 'kamuli': ['Balawoli',
            'Bugulumbya',
            'Bulopa',
            'Butansi',
            'Kagumba',
            'Kisozi',
            'Kitayunjwa',
            'Magogo',
            'Mbulamuti',
            'Nabwigulu',
            'Namasagali',
            'Namwendwa',
            'Nawanyago',
            'Northern Division',
            'Southern Division',
            'Wankole'],
 'kamwenge': ['Biguli',
              'Bihanga',
              'Busiriba',
              'Bwizi',
              'Kabambiro',
              'Kahunge',
              'Kahunge Town Council',
              'Kamwenge',
              'Kamwenge Town Council',
              'Nkoma',
              'Nkoma Town Council'],
 'kanungu': ['Butogota Town Council',
             'Kambuga',
             'Kambuga Town Council',
             'Kanungu Town Council',
             'Kanyantorogo',
             'Katete',
             'Kayonza',
             'Kihihi',
             'Kihiihi Town Council',
             'Kinaaba',
             'Kirima',
             'Mpungu',
             'Nyakinoni',
             'Nyamirama',
             'Nyanga',
             'Rugyeyo',
             'Rutenga'],
 'kapchorwa': ['Amukol',
               'Central Division',
               'Chema',
               'Chepterech',
               'Eastern Division',
               'Gamogo',
               'Kabeywa',
               'Kapsinda',
               'Kaptanya',
               'Kaserem',
               'Kawowo',
               'Munarya',
               'Sipi',
               'Western Division'],
 'karenga': ['Kapedo',
             'Karenga Town Council',
             'Kawalakol',
             'Lobalangit',
             'Lokori',
             'Napore Karenga',
             'Sangar'],
 'kasanda': ['Bukuya',
             'Kalwana',
             'Kassanda',
             'Kassanda Town Council',
             'Kiganda',
             'Kitumbi',
             'Makokoto',
             'Manyogaseka',
             'Myanzi',
             'Nalutuntu'],
 'kasese': ['Bugoye',
            'Buhuhira',
            'Bulembia Division',
            'Bwera',
            'Bwesumbu',
            'Central Division',
            'Hima Town Council',
            'Ihandiro',
            'Isango',
            'Karambi',
            'Karusandara',
            'Katwe Kabatoro Town Council',
            'Kilembe',
            'Kinyamasrke Town Council',
            'Kisinga',
            'Kisinga Town Council',
            'Kitholhu',
            'Kitswamba',
            'Kyabarungira',
            'Kyarumba',
            'Kyondo',
            'Lake Katwe',
            'Mahango',
            'Maliba',
            'Mpondwe-Lhubiriha',
            'Muhokya',
            'Munkunyu',
            'Nyakatonzi',
            'Nyakiyumbu',
            'Nyamwamba Division',
            'Rugendabara',
            'Rukoki'],
 'kayunga': ['Bbaale',
             'Busaana',
             'Galiraya',
             'Kangulumira',
             'Kayonza',
             'Kayunga',
             'Kayunga Town Council',
             'Kitimbwa',
             'Nazigo'],
 'kibaale': ['Bubango',
             'Bwamiramira',
             'Kabasekende',
             'Karama',
             'Kasimbi',
             'Kibaale Town Council',
             'Kyebando',
             'Matale',
             'Mugarama',
             'Nyamarunda',
             'Nyamarwa'],
 'kiboga': ['Bukomero',
            'Bukomero Town Council',
            'Ddwaniro',
            'Kapeke',
            'Kibiga',
            'Kiboga Town Council',
            'Lwamata',
            'Lwamata Town Council',
            'Muwanga'],
 'kibuku': ['Bulangira',
            'Buseta',
            'Goli Goli',
            'Kabweri',
            'Kadama',
            'Kagumu',
            'Kakutu',
            'Kasasira',
            'Kibuku',
            'Kibuku Town Council',
            'Kirika',
            'Kituti',
            'Lwamata',
            'Nabiswa',
            'Nandere',
            'Nankondo',
            'Tirinyi'],
 'kikuube': ['Bugambe',
             'Buhimba',
             'Buhimba Town Council',
             'Kabwoya',
             'Kikuube Town Council',
             'Kiziranfumbi',
             'Kyangwali'],
 'kiruhura': ['Kanyaryeru',
              'Kashongi',
              'Kenshunga',
              'Kikaatsi',
              'Kinoni',
              'Kiruhura Town Council',
              'Kitura',
              'Nyakashashara',
              'Sanga',
              'Sanga Town Council'],
 'kiryandongo': ['Bweyale Town Council',
                 'Kigumba',
                 'Kigumba Town Council',
                 'Kiryandongo',
                 'Kiryandongo Town Council',
                 'Masindi Port',
                 'Mutunda'],
 'kisoro': ['Bukimbiri',
            'Busanza',
            'Central',
            'Chahi',
            'Kanaba',
            'Kirundo',
            'Muramba',
            'Murora',
            'Northern',
            'Nyabwishenya',
            'Nyakabande',
            'Nyakinama',
            'Nyarubuye',
            'Nyarusiza',
            'Nyundo',
            'Rubuguri Town Council',
            'Southern'],
 'kitgum': ['Central Division',
            'Kitgum Matidi',
            'Labongo Akwang',
            'Labongo Amida',
            'Labongo Layamo',
            'Lagoro',
            'Mucwini',
            'Namokora',
            'Omiya Anyima',
            'Orom',
            'Pager Division',
            'Pandwong Division'],
 'koboko': ['Abuku',
            'Dranya',
            'Kuluba',
            'Lobule',
            'Ludara',
            'Midia',
            'Northern Divison',
            'Southern Division',
            'Western Division'],
 'kole': ['Aboke', 'Akalo', 'Alito', 'Ayer', 'Bala', 'Kole Town Council', 'Okwerodot'],
 'kotido': ['Central Division',
            'Kacheri',
            'Kotido',
            'Nakapelimoru',
            'North Division',
            'Panyangara',
            'Rengen',
            'South Division',
            'West Division'],
 'kumi': ['Atutur',
          'Kanyum',
          'Kumi',
          'Mukongoro',
          'Northern Divison',
          'Nyero',
          'Ongino',
          'Southern Division'],
 'kwania': ['Abongomola', 'Aduku', 'Aduku Town Council', 'Chawente', 'Inomo', 'Nambieso'],
 'kween': ['Benet',
           'Binyiny',
           'Binyiny Town Council',
           'Kaproron',
           'Kaproron Town Council',
           'Kaptoyoy',
           'Kaptum',
           'Kiriki',
           'Kitawoi',
           'Kwanyiy',
           'Kwosir',
           'Moyok',
           'Ngenge'],
 'kyankwanzi': ['Bananywa',
                'Banda',
                'Butemba',
                'Butemba Town Council',
                'Byerima',
                'Gayaza',
                'Kyankwanzi',
                'Kyankwanzi Town Council',
                'Mulagi',
                'Nkandwa',
                'Nsambya',
                'Ntwetwe',
                'Ntwetwe  Town Council',
                'Wattuba'],
 'kyegegwa': ['Hapuuyo',
              'Kabweza Kyegegwa',
              'Kakabara',
              'Kasule',
              'Kigambo',
              'Kyegegwa Town Council',
              'Mpara',
              'Ruyonza',
              'Rwentuha'],
 'kyenjojo': ['Bufunjo',
              'Bugaaki',
              'Butiiti',
              'Butunduzi',
              'Butunduzi Town Council',
              'Kanyegaramire',
              'Katooke',
              'Katooke Town Council',
              'Kigaraale',
              'Kihuura',
              'Kisojo',
              'Kyamutunzi Town Council',
              'Kyarusozi',
              'Kyarusozi  Town Council',
              'Kyembogo',
              'Kyenjojo Town Council',
              'Nyabiringo',
              'Nyabuharwa',
              'Nyankwanzi',
              'Nyantungo'],
 'kyotera': ['Kabira',
             'Kakuuto',
             'Kalisizo',
             'Kalisizo Town Council',
             'Kasaali Town Council',
             'Kasasa',
             'Kirumba',
             'Kyebe',
             'Kyotera Town Council',
             'Lwankoni',
             'Nabigasa',
             'Nangoma'],
 'lamwo': ['Agoro',
           'Lamwo Town Council',
           'Lokung',
           'Madi  Opei',
           'Padibe East',
           'Padibe Town Council',
           'Padibe West',
           'Palabek Gem',
           'Palabek Kal',
           'Palabek Ogili',
           'Paloga'],
 'lira': ['Adekokwok',
          'Adyel Division',
          'Agali',
          'Agweng',
          'Amach',
          'Aromo',
          'Barr',
          'Central Division',
          'Lira',
          'Ngetta',
          'Ogur',
          'Ojwina Division',
          'Railway Division'],
 'luuka': ['Bukanga',
           'Bukooma',
           'Bulongo',
           'Ikumbya',
           'Irongo',
           'Luuka Town Council',
           'Nawampiti',
           'Waibuga'],
 'luwero': ['Bamunanika',
            'Bombo Town Council',
            'Butuntumula',
            'Kalagala',
            'Kamira',
            'Katikamu',
            'Kikyusa',
            'Luwero',
            'Luwero Town Council',
            'Makulubita',
            'Nyimbwa',
            'Wobulenzi Town Council',
            'Zirobwe'],
 'lwengo': ['Kisekka',
            'Kkingo',
            'Kyazanga',
            'Kyazanga Town Council',
            'Lwengo',
            'Lwengo Town Council',
            'Malongo',
            'Ndagwe'],
 'lyantonde': ['Kaliiro',
               'Kasagama',
               'Kinuuka',
               'Lyakajura',
               'Lyantonde',
               'Lyantonde Town Council',
               'Mpumudde'],
 'madi-okollo': ['Anyiribu',
                 'Ewanga',
                 'Inde Town Council',
                 'Offaka',
                 'Ogoko',
                 'Okollo',
                 'Pawor',
                 'Rhino Camp',
                 'Rigbo',
                 'Uleppi'],
 'manafwa': ['Bugobero',
             'Bukhofu',
             'Bukusu',
             'Bunabwana',
             'Bunyinza Town Council',
             'Busukuya',
             'Butiru',
             'Butta',
             'Buwagogo',
             'Buwangani Town Council',
             'Kaato',
             'Khabutoola',
             'Manafwa Town Council',
             'Nalondo',
             'Sibanga',
             'Sisuni',
             'Weswa'],
 'maracha': ['Kijomoro',
             'Maracha Town Council',
             'Nyadri',
             'Oleba',
             'Oluffe',
             'Oluvu',
             'Tara',
             'Yivu'],
 'masaka': ['Bukakata',
            'Buwunga',
            'Kabonera',
            'Katwe-Butego Division',
            'Kimaanya-Kyabakuza Division',
            'Kyanamukaaka',
            'Kyesiiga',
            'Mukungwe',
            'Nyendo-Ssenyange Division'],
 'masindi': ['Budongo',
             'Bwijanga',
             'Central Division',
             'Karujubu Division',
             'Kigulya Division',
             'Kimengo',
             'Miirya',
             'Nyangahya Division',
             'Pakanyi'],
 'mayuge': ['Baitambogwe',
            'Bukabooli',
            'Bukatube',
            'Busakira',
            'Buwaaya',
            'Imanyiro',
            'Jaguzi',
            'Kigandalo',
            'Kityerera',
            'Magamaga Town Council',
            'Malongo',
            'Mayuge Town Council',
            'Mpungwe',
            'Wairasa'],
 'mbale': ['Bubyangu',
           'Budwale',
           'Bufumbo',
           'Bukasakya',
           'Bukiende',
           'Bukonde',
           'Bumasikye',
           'Bumbobi',
           'Bungokho',
           'Bungokho Mutoto',
           'Busano',
           'Busiu',
           'Busiu Town Council',
           'Busoba',
           'Industrial Divison',
           'Lukhonge',
           'Lwasso',
           'Nabumali Town Council',
           'Nakaloke',
           'Nakaloke Town Council',
           'Namambasa',
           'Namanyonyi',
           'Nawuyo Town Council',
           'Northern Division',
           'Nyondo',
           'Wanale',
           'Wanale Division'],
 'mbarara': ['Biharwe Division',
             'Bubaare',
             'Bukiro',
             'Kagongi',
             'Kakiika Division',
             'Kakoba Division',
             'Kamukuzi Division',
             'Kashare',
             'Nyakayojo Division',
             'Nyamitanga Division',
             'Rubaya',
             'Rubindi',
             'Rwanyamahembe'],
 'mitooma': ['Bitereko',
             'Kabira',
             'Kanyabwanga',
             'Kashenshero',
             'Kashenshero Town Council',
             'Katenga',
             'Kiyanga',
             'Mayanga',
             'Mitooma',
             'Mitooma Town Council',
             'Mutara',
             'Rurehe'],
 'mityana': ['Bbanda',
             'Bulera',
             'Busimbi Division',
             'Busunju Town Council',
             'Butayunja',
             'Central Division',
             'Kakindu',
             'Kalangaalo',
             'Kikandwa',
             'Maanyi',
             'Malangala',
             'Namungo',
             'Ssekanyonyi',
             'Ttamu Division'],
 'moroto': ['Katikekile', 'Nadunget', 'Northern Division', 'Rupa', 'Southern Divison', 'Tapac'],
 'moyo': ['Difule', 'Laropi', 'Lefori', 'Metu', 'Moyo', 'Moyo Town Council'],
 'mpigi': ['Buwama', 'Kammengo', 'Kiringente', 'Kituntu', 'Mpigi Town Council', 'Muduuma', 'Nkozi'],
 'mubende': ['Bagezza',
             'Butoloogo',
             'Eastern Division',
             'Kasambya',
             'Kasambya Town Council',
             'Kibalinga',
             'Kigando',
             'Kitenga',
             'Kiyuni',
             'Madudu',
             'Nabingoola',
             'Southern Division',
             'Western Division'],
 'mukono': ['Central Division',
            'Goma Division',
            'Kasawo',
            'Kimenyedde',
            'Koome Island',
            'Kyampisi',
            'Mpatta',
            'Mpunge',
            'Nabbaale',
            'Nagojje',
            'Nakisunga',
            'Nama',
            'Ntenjeru',
            'Ntunda',
            'Seeta Namuganga'],
 'nabilatuk': ['Lolachat', 'Lorengedwat', 'Nabilatuk', 'Nabilatuk Town Council'],
 'nakapiripirit': ['Kakomongole', 'Loregae', 'Moruita', 'Nakapiripirit Town Council', 'Namalu'],
 'nakaseke': ['Butalangu Town Council',
              'Kapeeka',
              'Kasangombe',
              'Kikamulo',
              'Kinoni',
              'Kinyogoga',
              'Kito',
              'Kiwoko Town Council',
              'Nakaseke',
              'Nakaseke Town Council',
              'Ngoma',
              'Ngoma Town Council',
              'Semuto',
              'Semuto Town Council',
              'Wakyato'],
 'nakasongola': ['Kakooge',
                 'Kakooge Town Council',
                 'Kalongo',
                 'Kalungi',
                 'Lwabiyata',
                 'Lwampanga',
                 'Migeera Town Council',
                 'Nabisweera',
                 'Nakasongola Town Council',
                 'Nakitoma',
                 'Wabinyonyi'],
 'namayingo': ['Banda',
               'Buhemba',
               'Bukana',
               'Buswale',
               'Buyinja',
               'Lolwe',
               'Mutumba',
               'Namayingo Town Council',
               'Sigulu Island'],
 'namisindwa': ['Bubutu',
                'Bukhabusi',
                'Bukhaweka',
                'Bukiabi',
                'Bukokho',
                'Bumbo',
                'Bumwoni',
                'Bupoto',
                'Buwabwala',
                'Lwakhakha Town Council',
                'Magale',
                'Magale Town Council',
                'Mukoto',
                'Namabya',
                'Namboko',
                'Namisindwa Town Council',
                'Tsekululu'],
 'namutumba': ['Bulange',
               'Ivukula',
               'Kibaale',
               'Magada',
               'Mazuba',
               'Nabweyo',
               'Namutumba',
               'Namutumba Town Council',
               'Nangonde',
               'Nsinze'],
 'napak': ['Iriiri',
           'Lokopo',
           'Lopeei',
           'Lorengecora',
           'Lotome',
           'Matany',
           'Napak Town Council',
           'Ngoleriet'],
 'nebbi': ['Abindu Division',
           'Akworo',
           'Atego',
           'Central Division',
           'Erussi',
           'Kucwiny',
           'Ndhew',
           'Nebbi',
           'Nyaravur',
           'Parombo',
           'Thatha Division'],
 'ngora': ['Kapir', 'Kobwin', 'Mukura', 'Ngora', 'Ngora Town Council'],
 'ntoroko': ['Butungama',
             'Bweramule',
             'Kanara',
             'Kanara Town Council',
             'Karugutu',
             'Karugutu Town Council',
             'Kibuuku Town Council',
             'Nombe',
             'Rwebisengo',
             'Rwebisengo Town Council'],
 'ntungamo': ['Bwongyera',
              'Central Division',
              'Eastern Division',
              'Ihunga',
              'Itojo',
              'Kafunjo-Mirama Town Council',
              'Kagarama Town Council',
              'Kayonza',
              'Kibatsi',
              'Kitwe Town Council',
              'Ngoma',
              'Ntungamo',
              'Nyabihoko',
              'Nyakyera',
              'Nyamunuka Town Council',
              'Rubaare',
              'Rubaare Town Council',
              'Rugarama',
              'Ruhaama',
              'Rukoni East',
              'Rukoni West',
              'Rwashamaire Town Council',
              'Rweikiniro',
              'Western Division'],
 'nwoya': ['Alero',
           'Anaka Payira',
           'Anaka Town Council',
           'Got Apwoyo',
           'Koch-Goma',
           'Lii',
           'Lungulu',
           'Purongo'],
 'obongi': ['Aliba', 'Gimara', 'Itula', 'Obongi Town Council'],
 'omoro': ['Bobi', 'Koro', 'Lakwana', 'Lalogi', 'Odek', 'Omoro Town Council', 'Ongako'],
 'otuke': ['Adwari', 'Alango', 'Ogor', 'Ogwette', 'Okwang', 'Olilim', 'Orum', 'Otuke Town Council'],
 'oyam': ['Aber',
          'Abok',
          'Acaba',
          'Aleka',
          'Iceme',
          'Kamdini',
          'Loro',
          'Minakulu',
          'Myene',
          'Ngai',
          'Otwal',
          'Oyam Town Council'],
 'pader': ['Acholibur',
           'Angagura',
           'Atanga',
           'Awere',
           'Laguti',
           'Lapul',
           'Latanya',
           'Ogom',
           'Pader',
           'Pader Town Council',
           'Pajule',
           'Puranga'],
 'pakwach': ['Alwi', 'Pakwach', 'Pakwach Town Council', 'Panyango', 'Panyimur', 'Wadelai'],
 'pallisa': ['Agule',
             'Akisim',
             'Apopong',
             'Chelekura',
             'Gogonyo',
             'Kameke',
             'Kamuge',
             'Kasodo',
             'Kibale',
             'Olok',
             'Opwateta',
             'Pallisa',
             'Pallisa Town Council',
             'Puti-Puti'],
 'rakai': ['Byakabanda',
           'Ddwaniro',
           'Kacheera',
           'Kagamba',
           'Kibanda',
           'Kifamba',
           'Kiziba',
           'Kyalulangira',
           'Lwamaggwa',
           'Lwanda',
           'Rakai Town Council'],
 'rubanda': ['Bubaare',
             'Bufundi',
             'Hamurwa',
             'Hamurwa Town Council',
             'Ikumba',
             'Muko',
             'Nyamweru',
             'Rubanda Town Council',
             'Ruhija'],
 'rubirizi': ['Katanda',
              'Katerera',
              'Katerera Town Council',
              'Katunguru',
              'Kichwamba',
              'Kirugu',
              'Kyabakara',
              'Magambo',
              'Rubiriziri Town Council',
              'Rutoto',
              'Ryeru'],
 'rukiga': ['Bukinda',
            'Kamwezi',
            'Kashambya',
            'Mparo Twon Council',
            'Muhanga Town Council',
            'Rwamucucu'],
 'rukungiri': ['Bugangari',
               'Buhunga',
               'Bukurungu Town Council',
               'Buyanja',
               'Buyanja Town Council',
               'Bwambara',
               'Eastern Divison',
               'Kebisoni',
               'Kebisoni Town Council',
               'Nyakagyeme',
               'Nyakishenyi',
               'Nyarushanje',
               'Ruhinda',
               'Rwerere Town Council',
               'Southern Division',
               'Western Division'],
 'sembabule': ['Lugusulu',
               'Lwebitakuli',
               'Lwemiyaga',
               'Mateete',
               'Mateete Town Council',
               'Mijwala',
               'Ntuusi',
               'Sembabule Town Council'],
 'serere': ['Atiira',
            'Bugondo',
            'Kadungulu',
            'Kadungulu Town Council',
            'Kasilo Town Council',
            'Kateta',
            'Kidetok Town Council',
            'Kyere',
            'Labori',
            'Olio',
            'Pingire',
            'Serere Town Council'],
 'sheema': ['Bugongi Town Council',
            'Kabwohe Division',
            'Kagango Division',
            'Kakindo Town Council',
            'Kasaana',
            'Kashozi Division',
            'Kigarama',
            'Kitagata',
            'Kitagata Town Council',
            'Kyangyenyi',
            'Masheruka',
            'Masheruka Twon Council',
            'Rugarama',
            'Sheema Central Division',
            'Shuuku Town Council'],
 'sironko': ['Budadiri Town Council',
             'Bugitimwa',
             'Buhugu',
             'Bukhulo',
             'Bukiise',
             'Bukiyi',
             'Bukyabo',
             'Bukyambi',
             'Bumalimba',
             'Bumasifwa',
             'Bunyafa',
             'Busulani',
             'Butandiga',
             'Buteza',
             'Buwalasi',
             'Buwasa',
             'Buyobo',
             'Masaba',
             'Nalusala',
             'Sironko Town Council',
             'Zesui'],
 'soroti': ['Arapai',
            'Asuret',
            'Eastern Division',
            'Gweri',
            'Kamuda',
            'Katine',
            'Northern Division',
            'Soroti',
            'Tubur',
            'Western Division'],
 'terego': ['Aii-Vu', 'Bileafe', 'Katrini', 'Manibe', 'Odupi', 'Omugo', 'Uriama'],
 'tororo': ['Eastern Division',
            'Iyolwa',
            'Kirewa',
            'Kisoko',
            'Kwapa',
            'Magola',
            'Malaba Town Council',
            'Mella',
            'Merikit',
            'Molo',
            'Mukuju',
            'Mulanda',
            'Nabuyoga',
            'Nagongera',
            'Nagongera Town Council',
            'Osukuru',
            'Paya',
            'Petta',
            'Rubongi',
            'Sop-Sop',
            'Western Division'],
 'wakiso': ['Bunamwaya Division',
            'Bussi',
            'Busukuma Division',
            'Bweyogerere Division',
            'Division A',
            'Division B',
            'Gombe Division',
            'Kajjansi Town Council',
            'Kakiri',
            'Kakiri Town Council',
            'Kasangati Town Council',
            'Kasanje',
            'Katabi  Town Council',
            'Kira Division',
            'Kyengera Town Council',
            'Masajja Division',
            'Masuliita',
            'Masulita Town Council',
            'Mende',
            'Nabweru Division',
            'Namayumba',
            'Namayumba Town Council',
            'Namugongo Division',
            'Nansana Division',
            'Ndejje Division',
            'Wakiso',
            'Wakiso Town Council'],
 'yumbe': ['Apo',
           'Ariwa',
           'Drajini',
           'Kei',
           'Kerwa',
           'Kochi',
           'Kululu',
           'Kuru',
           'Lodonga',
           'Midigo',
           'Odravu',
           'Romogi',
           'Yumbe Town Council'],
 'zombo': ['Abanga',
           'Akaa',
           'Alangi',
           'Athuma',
           'Atyak',
           'Jangokoro',
           'Kango',
           'Nyapea',
           'Paidha',
           'Paidha Town Council',
           'Warr',
           'Zeu',
           'Zombo Town Council']}
