# Generated by Django 4.2.30 on 2026-07-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactivitylog',
            name='platform',
            field=models.CharField(db_index=True, default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='adminactivitylog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
