# Generated by Django 4.2.30 on 2026-08-03 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0002_adminactivitylog_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPushBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'All users'), ('android', 'Android users'), ('ios', 'iOS users'), ('selected', 'Selected users')], max_length=20)),
                ('delivery_type', models.CharField(choices=[('announcement', 'Service announcement'), ('marketing', 'Marketing')], default='announcement', max_length=20)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('selected_user_ids', models.JSONField(blank=True, default=list)),
                ('matched_users', models.PositiveIntegerField(default=0)),
                ('targeted_devices', models.PositiveIntegerField(default=0)),
                ('accepted_devices', models.PositiveIntegerField(default=0)),
                ('rejected_devices', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_push_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
