"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import Config, Csv, RepositoryEnv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

ADMIN_BACKUP_ROOT = Path(
    config("ADMIN_BACKUP_ROOT", default=str(BASE_DIR / "admin_backups"))
)
ADMIN_BACKUP_TIMEOUT = config("ADMIN_BACKUP_TIMEOUT", default=900, cast=int)
PG_DUMP_BINARY = config("PG_DUMP_BINARY", default="pg_dump")
PG_RESTORE_BINARY = config("PG_RESTORE_BINARY", default="pg_restore")

_AFRICAS_TALKING_ENV_FILE = BASE_DIR / ".env.africas_talking"
_africas_talking_config = (
    Config(RepositoryEnv(str(_AFRICAS_TALKING_ENV_FILE)))
    if _AFRICAS_TALKING_ENV_FILE.exists()
    else config
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="unsafe-dev-secret-key")

DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
    cast=Csv(),
)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "corsheaders",
    "channels",

    "apps.common",
    "apps.accounts.apps.AccountsConfig",
    "apps.locations.apps.LocationsConfig",
    "apps.categories.apps.CategoriesConfig",
    "apps.listings.apps.ListingsConfig",
    "apps.favorites.apps.FavoritesConfig",
    "apps.chats.apps.ChatsConfig",
    "apps.notifications.apps.NotificationsConfig",
    "apps.moderation.apps.ModerationConfig",
    "apps.adminpanel.apps.AdminPanelConfig",
    "apps.seller.apps.SellerConfig",
    "apps.sellers.apps.SellersConfig",
    "apps.home.apps.HomeConfig",
    "apps.me.apps.MeConfig",
    "apps.searches.apps.SearchesConfig",
    "apps.reviews.apps.ReviewsConfig",
    "apps.payments.apps.PaymentsConfig",
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'apps.adminpanel.middleware.AdminActivityAuditMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("POSTGRES_DB", default="qot_prod"),
        "USER": config("POSTGRES_USER", default="qot_user"),
        "PASSWORD": config("POSTGRES_PASSWORD", default=""),
        "HOST": config("POSTGRES_HOST", default="127.0.0.1"),
        "PORT": config("POSTGRES_PORT", default="5432"),
        "CONN_MAX_AGE": 60,
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],

    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],

    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],

    "DEFAULT_PAGINATION_CLASS": "apps.common.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 20,
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

KEEP_SIGNED_IN_LIFETIME = timedelta(days=365)
GOOGLE_OAUTH_CLIENT_ID = config("GOOGLE_OAUTH_CLIENT_ID", default="")
FACEBOOK_OAUTH_APP_ID = config("FACEBOOK_OAUTH_APP_ID", default="")
FACEBOOK_OAUTH_APP_SECRET = config("FACEBOOK_OAUTH_APP_SECRET", default="")
FACEBOOK_GRAPH_API_VERSION = config(
    "FACEBOOK_GRAPH_API_VERSION",
    default="v25.0",
)

AFRICAS_TALKING_USERNAME = _africas_talking_config(
    "AFRICAS_TALKING_USERNAME",
    default="",
)
AFRICAS_TALKING_API_KEY = _africas_talking_config(
    "AFRICAS_TALKING_API_KEY",
    default="",
)
AFRICAS_TALKING_SENDER_ID = _africas_talking_config(
    "AFRICAS_TALKING_SENDER_ID",
    default="",
)
AFRICAS_TALKING_SANDBOX = _africas_talking_config(
    "AFRICAS_TALKING_SANDBOX",
    default=False,
    cast=bool,
)

PHONE_OTP_EXPIRY_MINUTES = config(
    "PHONE_OTP_EXPIRY_MINUTES",
    default=10,
    cast=int,
)
PHONE_OTP_RESEND_SECONDS = config(
    "PHONE_OTP_RESEND_SECONDS",
    default=60,
    cast=int,
)
PHONE_OTP_MAX_SENDS_PER_HOUR = config(
    "PHONE_OTP_MAX_SENDS_PER_HOUR",
    default=5,
    cast=int,
)
PHONE_OTP_MAX_ATTEMPTS = config(
    "PHONE_OTP_MAX_ATTEMPTS",
    default=5,
    cast=int,
)


REDIS_URL = config("REDIS_URL", default="redis://127.0.0.1:6379/0")


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
}


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # Channel receivers intentionally block while waiting for events.
            # redis-py 8 defaults socket_timeout to five seconds, which would
            # otherwise tear down every idle WebSocket connection.
            "hosts": [
                {
                    "address": REDIS_URL,
                    "socket_timeout": None,
                }
            ],
        },
    }
}


CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:3000,http://127.0.0.1:3000",
    cast=Csv(),
)

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="http://localhost:3000,http://127.0.0.1:3000",
    cast=Csv(),
)


FRONTEND_URL = config("FRONTEND_URL", default="http://qot.ug")

EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)

EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")

DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default="QOT <noreply@qot.ug>",
)

AUTH_USER_MODEL = "accounts.User"

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
