# Generated by Django 4.2.30 on 2026-06-25 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0003_alter_listing_status'),
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearchAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_search_alert_logs', to='listings.listing')),
                ('saved_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='searches.savedsearch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_search_alert_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['saved_search', 'listing'], name='searches_sa_saved_s_520989_idx'), models.Index(fields=['user', '-created_at'], name='searches_sa_user_id_6b6682_idx')],
                'unique_together': {('saved_search', 'listing', 'user')},
            },
        ),
    ]
