# Generated by Django 4.2.30 on 2026-07-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('listing_approved', 'Ad Approved'), ('listing_rejected', 'Ad Rejected'), ('listing_deleted', 'Ad Removed'), ('listing_expired', 'Ad Expired'), ('favorite', 'Ad Saved'), ('follow', 'New Follower'), ('system', 'System')], db_index=True, max_length=50),
        ),
    ]
