# Generated by Django 4.2.30 on 2026-08-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('listing_approved', 'Ad Approved'), ('listing_rejected', 'Ad Rejected'), ('listing_deleted', 'Ad Removed'), ('listing_expired', 'Ad Expired'), ('favorite', 'Ad Saved'), ('follow', 'New Follower'), ('review', 'New Review'), ('offer', 'Offer Update'), ('report', 'Report Update'), ('announcement', 'QOT Announcement'), ('system', 'System')], db_index=True, max_length=50),
        ),
    ]
